branches:
  only:
  - master
language: python
python:
- 2.7
install:
- pwd
- pip install -r requirements.txt
- pwd
- git clone https://github.com/cms-big-data/pelican-themes.git
- git clone --recursive https://github.com/getpelican/pelican-plugins
- pwd
- ls
- wget http://www.tipue.com/search/tipuesearch.zip
- unzip tipuesearch.zip
- cp -r Tipue\ Search\ 6.0/tipuesearch pelican-themes/static/
notifications:
  email:
    on_success: always
    on_failure: always
script:
- make -d html
env:
  global:
  - secure: Z3fZXmFeWOWVEk2esumwb3cx8b90t2UGwmbzmUtK22n87EH9JpvvBUEXXIzT3lPZ16Rx59e32sFrhP0d8IvUrWdqE7Oxmhd4Kpx0l/YmClZdZ8hFj0Lez/xV/75Z7Qbv/0rti0LWVxZUS4nV6W5JA1eiyO5SSeFmfAoIZHRjQ4Q+BMlGBSX8cO8XFwEmT7/iABqS8YRNzBErpVbT2TdXLzD8EAS59TYI/As2V+R4zRxX1VNZGai5UL7a7ZB6ctKf5XJWmh49C7W/t1fgO0cZYv9OVEezEuAn0m56FN8yBr+RVSvwru12FaxRNh3IOOArDdRJ3ztCeSsnpRBqG27KpXFg9Vcotf/r/n0x7haVmmN5YC+KcEpWDI2PQmpR7FXTtxxfMlZyO2Eevq+jYmQ1DUANclHb22Iv8KMWGd7ei8sjzLT3FxdnNBxrnEa+TP8hUH/53PrrFN+Olepcr/PhwGFCOmmHplzcwKpo9vfBs35E/Z4Zoy9BQj5W1hc7NynEwLALcYS3Bsj8Zjy5iOwM0/PMzqKTGsK4ciR89V0/63K7/Xxx/4syaQn/mkrBnmZNTdH3NzASnebGvGloxPtIyZ1q75gPFqUNM9yM4RmiqWQwglkkkkOfF724yjawPIDX8H26sXt/Hi257af+1xa7CRHDJl6xKw8r3SZmj6qeOZo=
before_install:
- git submodule update --init --recursive
after_success: bash deploy.sh
